# Generated by Django 3.2.10 on 2022-01-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stardin_video', '0002_auto_20220102_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=200)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='extra_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stardin_video.episode_data'),
        ),
    ]
