# Generated by Django 3.2.10 on 2022-01-02 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stardin_video', '0003_auto_20220102_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='extra_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stardin_video.episode_data'),
        ),
    ]
